### ISSUE TITLE
How to change tool tip text from 0 to 0% and 100 to 100%?

### ISSUE THREAD

**Issue by malik-umair** [9bitStudios/barfiller#2]
Hi, I need to change starting and ending bar text for just displaying 0 and 100 to 0% and 100% but didn't found any way to do this.

**Comment by 9bitStudios** [comment]
Hi malik-umair. I just added in a symbol setting that you could set to an empty string e.g. symbol: "" to remove the "%" character if you wanted to.

**Comment by malik-umair** [comment]
Hi, thanks for replying! where in the code i have to add characters? I didn't found symbol settings place. 

File: jquery.barfiller.js
* Version: 1.0.1

**Comment by 9bitStudios** [comment]
If you get the latest changeset there is a symbol setting option e.g. 

```javascript
$('#selector').barfiller({
    symbol: ""
});
```

**Comment by 9bitStudios** [comment]
Did this allow you to accomplish what you wanted to do?

**Comment by 9bitStudios** [comment]
I'm going to close this out. Please reopen if further action is needed.
